export interface ColorScheme {
    CONCEPTOS_BASICOS:'#FF2EC4',
    CONTROL_DE_VERSIONES:'#2EFCFF',
    JAVA:'FF902E',
    PYTHON:'#FF5900',
    CSHARP:'#FCFF2E',
    JAVASCRIPT:'#E1F00',
    DESARROLLO_WEB:'FF2E2E',
    DESARROLLO_MOVIL:'00E32A',
    DESARROLLO_MULTIPLATAFORMA:'#2E38FF',
    BASES_DE_DATOS:'#AB5722',
    INTELIGENCIA_ARTIFICIAL:'#AB2EFF',
    CLOUD_COMPUTING_SERVICES:'#FFD32E'

}